### ISSUE TITLE
This Hello world fails

### ISSUE THREAD

**Issue by rdebath** [nikp123/selfmodifying-brainfuck-interpreter#1]
You have a problem with your loop commands. 

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by nikp123** [comment]
Thanks, going to update right now.

**Comment by nikp123** [comment]
I forgot about nested loops, oops. Going to update right now.

**Comment by nikp123** [comment]
Updated the repo, it works for me.

**Comment by nikp123** [comment]
Nested loops now work.

**Comment by nikp123** [comment]
Sorry, forgot to push.

**Comment by rdebath** [comment]
They do indeed.
Next step would be to do some optimisations.
Say run-length-encoding and a jump table for starters.

**Comment by nikp123** [comment]
I'll try to do RLE for inc/dec and pointer shifting for starters. And see if I succeed.
